<?php

namespace app;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-06-05 at 08:40:08.
 */
class KkehFunctionTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var KkehFunction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new KkehFunction();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers app\KkehFunction::createOptionNum
     * @todo   Implement testCreateOptionNum().
     */
    public function testCreateOptionNum()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\KkehFunction::createOptionWor
     * @todo   Implement testCreateOptionWor().
     */
    public function testCreateOptionWor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\KkehFunction::createCheckbox
     * @todo   Implement testCreateCheckbox().
     */
    public function testCreateCheckbox()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\KkehFunction::connect
     * @todo   Implement testConnect().
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\KkehFunction::escape
     * @todo   Implement testEscape().
     */
    public function testEscape()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\KkehFunction::escapeLike
     */
    public function testEscapeLike()
    {
        $this->assertSame('小林#%', $this->object->escapeLike('小林%'));
        $this->assertSame('小林#_', $this->object->escapeLike('小林_'));
        $this->assertSame('小林#', $this->object->escapeLike('小林#'));
    }
}
